wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.15
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1683618645.535378
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.7.15
      5: 0.15.1
      8:
      - 2
      - 5
