wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.15
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1683191594.175154
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.7.15
      5: 0.15.1
      8:
      - 2
      - 5
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
val_percent:
  desc: null
  value: 0.1
save_checkpoint:
  desc: null
  value: true
img_scale:
  desc: null
  value: 0.3
amp:
  desc: null
  value: true
